export const dom = {
    leftLines          : document.getElementById('leftLines'),
    rightLines         : document.getElementById('rightLines'),
    unifiedLines       : document.getElementById('unifiedLines'),
    counter            : document.getElementById('counter'),
    prevBtn            : document.getElementById('prevBtn'),
    nextBtn            : document.getElementById('nextBtn'),
    restoreBtn         : document.getElementById('restoreBtn'),
    unifiedRestoreBtn  : document.getElementById('unifiedRestoreBtn'),
    openFileBtn        : document.getElementById('openFileBtn'),
    unifiedOpenFileBtn : document.getElementById('unifiedOpenFileBtn'),
    undoBtn            : document.getElementById('undoBtn'),
    viewToggle         : document.getElementById('viewToggle'),
    zoomOutBtn         : document.getElementById('zoomOutBtn'),
    zoomResetBtn       : document.getElementById('zoomResetBtn'),
    zoomInBtn          : document.getElementById('zoomInBtn'),
    scrollTopBtn       : document.getElementById('scrollTopBtn'),
    pinBtn             : document.getElementById('pinBtn'),
    clearPinBtn        : document.getElementById('clearPinBtn'),
    closeBtn           : document.getElementById('closeBtn'),
    diffContainer      : document.querySelector('.diff-container'),
    loadingIndicator   : document.querySelector('.loading-indicator'),
    hoverTooltip       : document.getElementById('hoverTooltip'),
    leftPane           : document.getElementById('leftPane'),
    rightPane          : document.getElementById('rightPane'),
    unifiedPane        : document.getElementById('unifiedPane'),
    timelineStrip      : document.getElementById('timelineStrip'),
    searchArea         : document.getElementById('searchArea'),
    searchInput        : document.getElementById('searchInput'),
    searchCounter      : document.getElementById('searchCounter'),
    searchPrevBtn      : document.getElementById('searchPrevBtn'),
    searchNextBtn      : document.getElementById('searchNextBtn'),
    searchCloseBtn     : document.getElementById('searchCloseBtn'),
    contextMenu        : document.getElementById('ctxMenu'),
}

dom.leftPaneBody = dom.leftPane.querySelector('.diff-pane-body')
dom.rightPaneBody = dom.rightPane.querySelector('.diff-pane-body')
